import Silver from "./components/silver-package";
import Gold from "./components/gold-package";
import Platinum from "./components/platinum-package";

export const CATEGORIES = [
  { id: "biriyani", label: "Biriyani & Rice", title: "Biriyani & Rice Specials" },
  { id: "starters", label: "Starters", title: "Starters" },
  { id: "desserts", label: "Desserts", title: "Desserts" },
  { id: "live", label: "Live Stalls", title: "Live Counters" },
];


export const MENU_ITEMS = [
  {
  id: "b1",
  name: "Chicken Biriyani",
  description: "Traditional dum chicken biriyani cooked with aromatic spices.",
  category: "biriyani",
  isVeg: false,
  isPopular: true,
  image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d35",
},
{
  id: "b2",
  name: "Mutton Biriyani",
  description: "Slow-cooked dum mutton biriyani with rich, bold flavors.",
  category: "biriyani",
  isVeg: false,
  isPopular: true,
  image: "https://images.unsplash.com/photo-1701579231349-d7459c40919d",
},
{
  id: "b3",
  name: "Chicken Pulao",
  description: "Lightly spiced pulao with tender chicken pieces.",
  category: "biriyani",
  isVeg: false,
  image: "https://images.unsplash.com/photo-1627662168223-7df99068099a",
},
{
  id: "b4",
  name: "Mutton Pulao",
  description: "Fragrant pulao cooked with soft, slow-cooked mutton.",
  category: "biriyani",
  isVeg: false,
  image: "https://images.unsplash.com/photo-1668508931618-efb7dbb3d2e3",
},

  {
    id: "b5",
    name: "Chicken Hyderabadi Biriyani",
    description: "Authentic Hyderabadi-style dum biriyani.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "chickenhyderabad.j",
  },
  {
    id: "b6",
    name: "Ghee Rice with Mutton Nihari",
    description: "Fragrant ghee rice paired with slow-cooked mutton nihari.",
    category: "biriyani",
    isVeg: false,
    image: "/gheerice.jpg",
  },
  {
    id: "b7",
    name: "Chicken Mandi",
    description: "Smoky Arabic-style rice with tender chicken.",
    category: "biriyani",
    isVeg: false,
    image: "/chickenmandi.jpg",
  },
  {
    id: "b8",
    name: "Mutton Mandi",
    description: "Slow-cooked mutton mandi with rich Arabian flavors.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "/MuttonMandi.jpg",
  },
  {
    id: "b9",
    name: "afgani Pulao",
    description: "Afghan-style pulao with dry fruits and mild spices.",
    category: "biriyani",
    isVeg: false,
    image: "/afganipulao.jpg",
  },


  // 🔥 STARTERS
  {
    id: "s1",
    name: "Chicken 65",
    description:
      "Crispy, spicy deep-fried chicken tossed in South Indian spices.",
    image: "/chicken65.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s2",
    name: "Afgani Kebab",
    description: "Juicy kebabs marinated in Afghan spices.",
    category: "starters",
    isVeg: false,
    isPopular: true,
    image: "/afganichicken.jpg",
  },
  {
    id: "s3",
    name: "Turkey Kebab",
    description: "Grilled turkey kebabs with bold smoky flavors.",
    category: "starters",
    isVeg: false,
    isPopular: true,
    image: "/turkeykebab.jpg",
  },

  {
    id: "s4",
    name: "Chicken Lollipop",
    description: "Frenched chicken wings marinated and fried to perfection.",
    image: "/chickenlolli.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s5",
    name: "Mutton Chops",
    description: "Juicy mutton chops slow-cooked with aromatic spices.",
    image: "/muttonchops.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s6",
    name: "Fish Finger",
    description: "Crispy breaded fish fingers served golden and crunchy.",
    image: "/fishfinger.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s7",
    name: "Chicken Popcorn",
    description: "Bite-sized crunchy chicken popcorn with mild seasoning.",
    image: "/chickenpopcorn.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s8",
    name: "Chicken Tikka",
    description: "Char-grilled chicken cubes marinated in yogurt and spices.",
    image: "/chickentikka.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s9",
    name: "Prawn Pepper Fry",
    description: "Spicy prawn fry tossed with cracked pepper and curry leaves.",
    image: "/prawnpepperfry.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s10",
    name: "Fish Tikka",
    description: "Soft fish cubes marinated and grilled in tandoor style.",
    image: "/fishtikka.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s11",
    name: "Chicken Cutlets",
    description: "Crispy shallow-fried cutlets with spiced minced chicken meat.",
    image: "/chickencutlets.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s12",
    name: "Pepper Chicken Dry",
    description: "Hot and spicy pepper chicken tossed in South Indian style.",
    image: "/pepperchicken.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s13",
    name: "Prawn 65",
    description: "Crispy fried prawns coated in signature 65 masala.",
    image: "prawn65.jpg",
    isVeg: false,
    category: "starters",
  },
  {
    id: "s14",
    name: "Mutton Cutlets",
    description: "Perfectly spiced mutton, pan-fried for a rich crunch.",
    image: "/muttoncutlets.jpg",
    isVeg: false,
    category: "starters",
  },

  // 🍨 DESSERTS
   {
    id: "d1",
    name: "Bread Halwa",
    description: "Rich, ghee-loaded traditional dessert.",
    category: "desserts",
    isVeg: true,
    image: "/breadhalwa.jpg",
  },
  {
    id: "d2",
    name: "Pineapple Kesari",
    description: "Soft semolina dessert with pineapple flavor.",
    category: "desserts",
    isVeg: true,
    isPopular: true,
    image: "/pineapplekesari.jpg",
  },
  {
    id: "d3",
    name: "Rasa Malai",
    description: "Soft cheese dumplings soaked in saffron milk.",
    category: "desserts",
    isVeg: true,
    image: "/rasamolai.jpg",
  },
  {
    id: "d4",
    name: "Elaneer Payasam",
    description: "Tender coconut dessert with mild sweetness.",
    category: "desserts",
    isVeg: true,
    image: "/ilaneerpayasam.jpg",
  },
  {
    id: "d5",
    name: "Gulab Jamun",
    description: "Soft fried milk dumplings soaked in sugar syrup.",
    category: "desserts",
    isVeg: true,
    image: "/gulabjamun.jpg",
  },
  {
    id: "d6",
    name: "Maska Bun",
    description: "Warm bun served with melting butter.",
    category: "desserts",
    isVeg: true,
    isPopular: true,
    image: "/maskabun.jpg",
  },
    // 🎪 LIVE STALLS
  {
    id: "l1",
    name: "Pani Puri",
    description: "Live counter with fresh, tangy pani puri.",
    category: "live",
    isVeg: true,
    image: "/panipuri.jpg",
  },
  {
    id: "l2",
    name: "Popcorn",
    description: "Freshly popped buttery popcorn.",
    category: "live",
    isVeg: true,
    image: "/popcorn.jpg",
  },
  {
    id: "l3",
    name: "Cotton Candy",
    description: "Fluffy, colorful cotton candy delight.",
    category: "live",
    isVeg: true,
    image: "/cottoncandy.jpg",
  },
  {
    id: "l4",
    name: "Ice Cream",
    description: "Multiple flavors served live.",
    category: "live",
    isVeg: true,
    image: "/icecream.png",
  },
  {
    id: "l5",
    name: "Fruit Salad",
    description: "Fresh seasonal fruits served chilled.",
    category: "live",
    isVeg: true,
    image: "/fruitsalad.jpg",
  },
  {
    id: "l6",
    name: "Mocktail Bar",
    description: "Refreshing mocktails mixed live.",
    category: "live",
    isVeg: true,
    isPopular: true,
    image: "/mocktail.jpg",
  },
  {
    id: "l7",
    name: "Chocolate Fountain",
    description: "Flowing chocolate with fruits & treats.",
    category: "live",
    isVeg: true,
    isPopular: true,
    image: "/chocolatefountain.jpg",
  },
];

export const PACKAGES = [
  {
    id: "silver",
    name: "Silver Package",
    description: "Perfect for small family functions and intimate gatherings.",
    icon: Silver,
    items: ["s1", "s2", "m1", "m4", "d1"],
    features: [
      { label: "Starters", value: "2 Items" },
      { label: "Main Course", value: "2 Rice Items" },
      { label: "Dessert", value: "1 Item" },
    ],
  },

  {
    id: "gold",
    name: "Gold Package",
    description: "Ideal for weddings and medium-sized celebrations.",
    icon: Gold,
    isPopular: true,
    items: ["s1", "s2", "s3", "m1", "m2", "m4", "d1", "l2"],
    features: [
      { label: "Starters", value: "3 Items" },
      { label: "Biriyani", value: "Chicken & Mutton" },
      { label: "Live Counter", value: "Ice Cream" },
      { label: "Dessert", value: "1 Item" },
    ],
  },

  {
    id: "platinum",
    name: "Platinum Package",
    description: "Premium experience with live counters and full spread.",
    icon: Platinum,
    items: [
      "s1",
      "s2",
      "s3",
      "s4",
      "m1",
      "m2",
      "m3",
      "m4",
      "m5",
      "m6",
      "d1",
      "l1",
      "l2",
      "l3",
    ],
    features: [
      { label: "Starters", value: "4 Items" },
      { label: "Biriyani", value: "Chicken, Mutton & Beef" },
      { label: "Live Counters", value: "Salad, Ice Cream & Fruits" },
      { label: "Dessert", value: "Included" },
    ],
  },
];
