import Silver from "./components/silver-package";
import Gold from "./components/gold-package";
import Platinum from "./components/platinum-package";

export const CATEGORIES = [
  { id: "biriyani", label: "Biriyani & Rice", title: "Biriyani & Rice Specials" },
  { id: "starters", label: "Starters", title: "Starters" },
  { id: "desserts", label: "Desserts", title: "Desserts" },
  { id: "live", label: "Live Stalls", title: "Live Counters" },
];

export const MENU_ITEMS = [
  // 🍚 BIRIYANI & RICE
  {
    id: "b1",
    name: "Chicken Biriyani",
    description: "Traditional dum chicken biriyani cooked with aromatic spices.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "/chickenbiriyani.jpg",
  },
  {
    id: "b2",
    name: "Mutton Biriyani",
    description: "Slow-cooked dum mutton biriyani with rich, bold flavors.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "/muttonbiriyani.jpg",
  },
  {
    id: "b3",
    name: "Chicken Pulao",
    description: "Lightly spiced pulao with tender chicken pieces.",
    category: "biriyani",
    isVeg: false,
    image: "/chickenpulao.jpg",
  },
  {
    id: "b4",
    name: "Mutton Pulao",
    description: "Fragrant pulao cooked with soft, slow-cooked mutton.",
    category: "biriyani",
    isVeg: false,
    image: "/muttonpulao.jpg",
  },
  {
    id: "b5",
    name: "Chicken Hyderabadi Biriyani",
    description: "Authentic Hyderabadi-style dum biriyani.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "/chickenhyderabad.jpg",
  },
  {
    id: "b6",
    name: "Ghee Rice with Mutton Nihari",
    description: "Fragrant ghee rice paired with slow-cooked mutton nihari.",
    category: "biriyani",
    isVeg: false,
    image: "/gheerice.jpg",
  },
  {
    id: "b7",
    name: "Chicken Mandi",
    description: "Smoky Arabic-style rice with tender chicken.",
    category: "biriyani",
    isVeg: false,
    image: "/chickenmandi.jpg",
  },
  {
    id: "b8",
    name: "Mutton Mandi",
    description: "Slow-cooked mutton mandi with rich Arabian flavors.",
    category: "biriyani",
    isVeg: false,
    isPopular: true,
    image: "/muttonmandi.jpg",
  },
  {
    id: "b9",
    name: "Afgani Pulao",
    description: "Afghan-style pulao with dry fruits and mild spices.",
    category: "biriyani",
    isVeg: false,
    image: "/afganipulao.jpg",
  },

  // 🔥 STARTERS
  {
    id: "s1",
    name: "Chicken 65",
    description: "Crispy, spicy deep-fried chicken tossed in South Indian spices.",
    category: "starters",
    isVeg: false,
    image: "/chicken65.jpg",
  },
  {
    id: "s2",
    name: "Afgani Kebab",
    description: "Juicy kebabs marinated in Afghan spices.",
    category: "starters",
    isVeg: false,
    isPopular: true,
    image: "/afghanichicken.jpg",
  },
  {
    id: "s3",
    name: "Turkey Kebab",
    description: "Grilled turkey kebabs with bold smoky flavors.",
    category: "starters",
    isVeg: false,
    isPopular: true,
    image: "/turkeykebab.jpg",
  },
  {
    id: "s5",
    name: "Mutton Chops",
    description: "Juicy mutton chops slow-cooked with aromatic spices.",
    category: "starters",
    isVeg: false,
    image: "/muttonchops.jpg",
  },

  // 🍨 DESSERTS
  {
    id: "d1",
    name: "Bread Halwa",
    description: "Rich, ghee-loaded traditional dessert.",
    category: "desserts",
    isVeg: true,
    image: "/breadhalwa.jpg",
  },
  {
    id: "d2",
    name: "Pineapple Kesari",
    description: "Soft semolina dessert with pineapple flavor.",
    category: "desserts",
    isVeg: true,
    isPopular: true,
    image: "/pineapplekesari.jpg",
  },
  {
    id: "d6",
    name: "Maska Bun",
    description: "Warm bun served with melting butter.",
    category: "desserts",
    isVeg: true,
    isPopular: true,
    image: "/maskabun.jpg",
  },

  // 🎪 LIVE STALLS
  {
    id: "l1",
    name: "Pani Puri",
    description: "Live counter with fresh, tangy pani puri.",
    category: "live",
    isVeg: true,
    image: "/panipuri.jpg",
  },
  {
    id: "l4",
    name: "Ice Cream",
    description: "Multiple flavors served live.",
    category: "live",
    isVeg: true,
    image: "/icecream.png",
  },
  {
    id: "l6",
    name: "Mocktail Bar",
    description: "Refreshing mocktails mixed live.",
    category: "live",
    isVeg: true,
    isPopular: true,
    image: "/mocktail.jpg",
  },
  {
    id: "l7",
    name: "Chocolate Fountain",
    description: "Flowing chocolate with fruits & treats.",
    category: "live",
    isVeg: true,
    isPopular: true,
    image: "/chocolatefountain.jpg",
  },
];

export const PACKAGES = [
  {
    id: "silver",
    name: "Silver Package",
    description: "Ideal for small family functions and intimate gatherings.",
    icon: Silver,
    items: ["s1", "s2", "b1", "b3", "d1"],
    features: [
      { label: "Starters", value: "2 Non-Veg Items" },
      { label: "Rice Selection", value: "Chicken Biriyani & Pulao" },
      { label: "Dessert", value: "1 Traditional Sweet" },
    ],
  },

  {
    id: "gold",
    name: "Gold Package",
    description: "Perfect for weddings and medium-sized celebrations.",
    icon: Gold,
    isPopular: true,
    items: ["s1", "s2", "s3", "b1", "b2", "b5", "d2", "l4"],
    features: [
      { label: "Starters", value: "3 Premium Non-Veg Items" },
      { label: "Biriyani Selection", value: "Chicken & Mutton Varieties" },
      { label: "Dessert", value: "Popular Traditional Sweet" },
      { label: "Live Counter", value: "Ice Cream Stall" },
    ],
  },

  {
    id: "platinum",
    name: "Platinum Package",
    description: "Luxury catering experience with premium spread & live counters.",
    icon: Platinum,
    items: [
      "s1",
      "s2",
      "s3",
      "s5",
      "b1",
      "b2",
      "b5",
      "b7",
      "b8",
      "d2",
      "d6",
      "l1",
      "l4",
      "l6",
      "l7",
    ],
    features: [
      { label: "Starters", value: "4 Elite Non-Veg Dishes" },
      { label: "Rice & Biriyani", value: "Biriyani, Mandi & Special Rice" },
      {
        label: "Live Counters",
        value: "Pani Puri, Ice Cream, Mocktails & Chocolate Fountain",
      },
      { label: "Desserts", value: "Multiple Premium Sweets" },
    ],
  },
];
